export { Nexora } from './nexora.js';
export type { NexoraOptions, LifecyclePhase } from './nexora.js';

export {
  DEFAULT_COMMAND_ERROR_MESSAGE,
  DEFAULT_INTERACTION_ERROR_MESSAGE,
  DEFAULT_DEFER_ERROR_MESSAGE,
  resolveErrorMessage,
  reportError,
  formatErrorMessage,
} from './errors/index.js';
export type {
  NexoraErrorSource,
  NexoraErrorContext,
  NexoraErrorHandler,
  ErrorBoundaryConfig,
} from './errors/index.js';

export { Container, TOKENS } from './container/index.js';
export type { ServiceToken, ServiceFactory } from './container/index.js';

export {
  command,
  slash,
  messageCommand,
  createCommandContext,
  createMessageCommandContext,
  resolveReplyOptions,
  withDefaultEphemeral,
  createCommandOptionsGetters,
  SlashCommand,
  BaseCommand,
  isCommandClass,
  resolveCommandExport,
  SlashCommandGroup,
  SlashCommandSubGroup,
  subcommands,
  group,
  isCommandGroupClass,
  resolveCommandGroupExport,
  ContextMenuCommand,
  createContextMenuContext,
  isContextMenuClass,
  resolveContextMenuExport,
  CommandRegistry,
  discoverCommands,
  deployCommands,
  attachCommandHandlers,
  stringOpt,
  integerOpt,
  numberOpt,
  booleanOpt,
  userOpt,
  channelOpt,
  roleOpt,
  mentionableOpt,
  attachmentOpt,
  Guards,
  guildOnly,
  adminOnly,
  ownerOnly,
  hasPermissions,
  userIds,
  and,
  or,
  runGuards,
  composeCommandMiddleware,
  autocomplete,
  AutocompleteHandler,
  createAutocompleteContext,
  choicesFrom,
  AUTOCOMPLETE_MAX_CHOICES,
  buildStatusReply,
} from './commands/index.js';
export type {
  CommandDefinition,
  CommandContext,
  CommandOption,
  CommandModuleType,
  MessageCommandDefinition,
  MessageCommandContext,
  CommandReplyOptions,
  BuilderReplyOptions,
  CreateCommandContextOptions,
  StatusReplyOptions,
  CommandOptionsGetters,
  ContextMenuType,
  ContextMenuContext,
  ContextMenuCommandDefinition,
  RegisteredCommand,
  RegisteredCommandGroup,
  RegisteredSubGroup,
  RegisteredContextMenu,
  AttachCommandHandlersOptions,
  SlashCommandConstructor,
  GroupOptions,
  OptionChoice,
  BaseOptionConfig,
  StringOptionConfig,
  IntegerOptionConfig,
  NumberOptionConfig,
  BooleanOptionConfig,
  UserOptionConfig,
  ChannelOptionConfig,
  RoleOptionConfig,
  MentionableOptionConfig,
  AttachmentOptionConfig,
  AutocompleteChoice,
  AutocompleteContext,
  Guard,
  GuardResult,
  CommandMiddleware,
  CommandContextServices,
  RunGuardsOptions,
  ComposeCommandMiddlewareOptions,
} from './commands/index.js';

export {
  event,
  on,
  onReady,
  EventHandler,
  isEventClass,
  resolveEventExport,
  EventRegistry,
  discoverEvents,
  attachEventHandlers,
} from './events/index.js';
export type {
  EventDefinition,
  EventExecuteFn,
  RegisteredEvent,
} from './events/index.js';

export {
  createComponentContext,
  createModalContext,
  ButtonHandler,
  button,
  isButtonHandlerClass,
  resolveButtonHandlerExport,
  SelectHandler,
  StringSelectHandler,
  select,
  isSelectHandlerClass,
  resolveSelectHandlerExport,
  ModalHandler,
  modal,
  isModalHandlerClass,
  resolveModalHandlerExport,
  InteractionRegistry,
  expandCustomIdVariants,
  isPrefixMatch,
  attachInteractionHandlers,
  discoverInteractions,
} from './interactions/index.js';
export type {
  ComponentContext,
  ModalContext,
  BaseInteractionContext,
  ComponentInteraction,
  InteractionReplyInput,
  InteractionUpdateInput,
  InteractionHandlerKind,
  AnyInteractionHandler,
  RegisteredInteraction,
  InteractionRegistryGetOptions,
  AttachInteractionHandlersOptions,
} from './interactions/index.js';

export { EventBus, FrameworkEvents } from './event-bus/index.js';
export type { HookPhase, Middleware } from './event-bus/index.js';

export { Cache, MemoryCacheAdapter } from './cache/index.js';
export type { CacheAdapter } from './cache/index.js';

export { Scheduler } from './scheduler/index.js';
export type { ScheduledJob } from './scheduler/index.js';

export { Service, createService, registerService } from './services/index.js';
export type { ServiceContext } from './services/index.js';

export {
  EmbedPaginator,
  Paginator,
  ConfirmDialog,
  ChoicePrompt,
} from './prompts/index.js';
export type {
  PromptContext,
  PromptSendOptions,
  PaginatorOptions,
  PaginatorPage,
  ConfirmDialogOptions,
  ChoicePromptOptions,
  ChoicePromptOption,
} from './prompts/index.js';

export {
  EmbedBuilder,
  Embed,
  EmbedColor,
  resolveColor,
  ButtonBuilder,
  btn,
  ActionRowBuilder,
  row,
  StringSelectBuilder,
  UserSelectBuilder,
  RoleSelectBuilder,
  MentionableSelectBuilder,
  ChannelSelectBuilder,
  ModalBuilder,
  TextInputBuilder,
  customId,
  resolveCustomId,
  packCustomId,
  parseCustomId,
  CUSTOM_ID_NAMESPACE,
  CUSTOM_ID_DELIMITER,
  CUSTOM_ID_MAX_LENGTH,
  ComponentType,
  ButtonStyle,
  TextInputStyle,
  ChannelType,
  V2ComponentType,
  IsComponentsV2,
  MAX_V2_COMPONENTS,
  SeparatorSpacing,
  toAPI,
  countComponents,
  resolveAccentColor,
  attachmentUrl,
  TextDisplayBuilder,
  text,
  ThumbnailBuilder,
  thumbnail,
  SectionBuilder,
  section,
  MediaGalleryBuilder,
  gallery,
  mediaGallery,
  SeparatorBuilder,
  separator,
  FileBuilder,
  file,
  LayoutContainerBuilder,
  MessageContainerBuilder,
  container,
  LabelBuilder,
  label,
  ComponentsV2Message,
  v2Message,
  ComponentsV2,
} from './builders/index.js';
export type {
  EmbedData,
  SelectOptionInput,
  CustomIdOptions,
  ComponentTypeValue,
  ButtonStyleValue,
  TextInputStyleValue,
  ChannelTypeValue,
  ColorResolvable,
  JSONEncodable,
  EmbedLike,
  ComponentLike,
  APIEmbed,
  APIEmbedField,
  APIEmbedFooter,
  APIEmbedAuthor,
  APIEmbedMedia,
  APIPartialEmoji,
  APIButtonComponent,
  APISelectOption,
  APISelectDefaultValue,
  APIStringSelectComponent,
  APIUserSelectComponent,
  APIRoleSelectComponent,
  APIMentionableSelectComponent,
  APIChannelSelectComponent,
  APISelectMenuComponent,
  APITextInputComponent,
  APIActionRowComponent,
  APIModalComponent,
  APIMessageActionRowComponent,
  APIModalActionRowComponent,
  V2ComponentTypeValue,
  SeparatorSpacingValue,
  UnfurledMediaItem,
  APITextDisplayComponent,
  APIThumbnailComponent,
  APIMediaGalleryItem,
  APIMediaGalleryComponent,
  APIFileComponent,
  APISeparatorComponent,
  APISectionComponent,
  APIContainerComponent,
  APILabelComponent,
  ComponentsV2MessagePayload,
  SectionAccessory,
  MediaGalleryItemInput,
  SeparatorOptions,
  ComponentsV2CardOptions,
} from './builders/index.js';

export {
  checkForCoreUpdate,
  fetchLatestCoreVersion,
  getInstalledCoreVersion,
  isNewerVersion,
} from './update-check.js';
export type { UpdateCheckResult } from './update-check.js';

export {
  studioTelemetry,
  getStudioTelemetry,
  StudioTelemetry,
  PipelineTraceBuilder,
  nextTelemetryId,
} from './studio-telemetry/index.js';
export type {
  StudioEventHandlerSpan,
  StudioEventTrace,
  PipelineStepKind,
  StudioPipelineStep,
  StudioPipelineTrace,
  StudioCommandMetrics,
  StudioPerformanceSnapshot,
  RecordCommandResultInput,
} from './studio-telemetry/index.js';
